targets:
  $default:
    builders:
      proxy_generator|proxy:
        enabled: true

builders:
  proxy:
    target: ":proxy_generator"
    import: "package:proxy_generator/builder.dart"
    builder_factories: ["proxyBuilder"]
    build_extensions: {".dart": [".proxy.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
