name: proxy_generator
version: 0.0.0
description: >
  Proxy objects based code generation instead of reflection.
  (entirely not related to internet proxies)
  This library is the runtime dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  proxy:
    path: ../proxy
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0

dev_dependencies:
  build_runner:
  rmi_test:
    path: ../test  
  test:
