targets:
  $default:
    builders:
      rmi_generator|rmi:
        enabled: true

builders:
  rmi:
    target: ":rmi_generator"
    import: "package:rmi_generator/builder.dart"
    builder_factories: ["rmiBuilder", 'proxyBuilder', 'invokerBuilder']
    build_extensions: {".dart": [".rmi.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]