name: rmi_generator
version: 0.0.4
description: >
  Remote Method Invocation without reflection but basd on code generation.
  This is the dev dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0
  
dev_dependencies:
  json_annotation:

dependency_overrides:
  source_gen_helpers: 