name: rmi_generator
version: 0.0.1
description: >
  This library is the dev dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  rmi: 0.0.1
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0
  built_value: ^6.1.6
  built_collection: ^4.1.0
  
dev_dependencies:
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2
  test: ^1.5.1

# dependency_overrides:
#   rmi:
#     path: ../rmi
