name: type_identifier
version: 0.0.0
description: >
  TODO
  This library is the runtime dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  meta: ^1.0.4
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.1.6
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0