name: type_identifier_generator
version: 0.0.0
description: >
  TODO
  This library is the dev dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  type_identifier:
    path: ../type_identifier
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0