name: rmi
version: 0.0.4
description: >
  Remote Method Invocation without reflection but basd on code generation.
  This library is the runtime dependency. Additionally add `rmi__generator` as dev dependency. 
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  uuid: ^1.0.3
  json_annotation:
  json_serialization:
    git: 
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serialization
  
dev_dependencies:
  build_runner: ^1.1.2
  json_serializable:
    git:
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serializable
