name: rmi
version: 0.0.2
description: >
  Remote Method Invocation without reflection but basd on code generation.
  This library is the runtime dependency. Additionally add `rmi__generator` as dev dependency. 
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  uuid: ^1.0.3
  built_value: ^6.1.6
  built_collection: ^4.1.0
  
dev_dependencies:
  built_value_generator: ^6.1.6
  build_runner: ^1.1.2

