#!/bin/bash
set -e

cd rmi;
pub get
pub upgrade
pub run build_runner build \
  --delete-conflicting-outputs \
  --fail-on-severe
dartfmt -w . 
dartanalyzer \
  --fatal-warnings \
  --fatal-infos \
  .
cd ..;

cd rmi_generator;
pub get
pub upgrade
dartfmt -w .
dartanalyzer \
  --fatal-warnings \
  --fatal-infos \
  --no-hints \
  .
cd ..;

cd rmi_tests;
pub get
pub upgrade
pub run build_runner build \
  --delete-conflicting-outputs \
  --fail-on-severe
dartfmt -w .
dartanalyzer \
  --fatal-warnings \
  --fatal-infos \
  --no-hints \
  .
pub run test --platform vm;
pub run test --platform chrome;
pub run test --platform node;
cd ..;

cd example;
pub get
pub upgrade
pub run build_runner build \
  --delete-conflicting-outputs \
  --fail-on-severe
dartfmt -w .
dartanalyzer \
  --fatal-warnings \
  --fatal-infos \
  --no-hints \
  .
dart lib/example.dart
cd ..;

