#!/bin/bash
set -e

target=( rmi rmi_generator )
resource=( README.md LICENSE example CHANGELOG.md )
for i in "${target[@]}"
do      
      for j in "${resource[@]}"
      do      
            cp -r $j $i 
      done       
done 