#!/bin/bash
set -e

if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]
then
      echo 'ERROR: git repo is not clean';
      exit 1;
fi

target=( rmi rmi_generator )
resource=( README.md LICENSE example CHANGELOG.md )
for i in "${target[@]}"
do      
      for j in "${resource[@]}"
      do      
            cp -r $j $i 
      done       
done 

cd rmi;
pub publish;
cd ..;
cd rmi_generator;
pub publish;
cd ..;

git clean -f -d