targets:
  $default:
    builders:
      invoker_generator|invoker:
        enabled: true

builders:
  invoker:
    target: ":invoker_generator"
    import: "package:invoker_generator/builder.dart"
    builder_factories: ["invokerBuilder"]
    build_extensions: {".dart": [".invoker.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
