name: invoker_generator
version: 0.0.0
description: >
  Invoker objects can invoke methods on an object given an Invokation parameter.
  This library is the dev dependency.
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  invoker:
    path: ../invoker
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0