targets:
  $default:
    builders:
      remote_method_invocation_generator|remote_method_invocation:
        enabled: true

builders:
  remote_method_invocation:
    target: ":remote_method_invocation_generator"
    import: "package:remote_method_invocation_generator/builder.dart"
    builder_factories: ["rmiBuilder"]
    build_extensions: {".dart": [".rmi.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]