name: rmi_tests
version: 0.0.0
description: >
  TODO, do not publish, update presubmit
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.3
  build: ^1.0.0
  tuple:
  build_config: ^0.3.1
  source_gen: ^0.9.0
  built_value: ^6.1.6
  built_collection: ^4.1.0
  build_runner: ^1.1.2
  rmi:
    path: ../rmi
  
dev_dependencies:
  json_serializable:
  rmi_generator:
    path: ../rmi_generator
  source_gen_helpers: ^0.0.1
  test: ^1.5.1

dependency_overrides:
  source_gen_helpers: 
    path: ../../source_gen_helpers
  json_serializable:
    path: ../../json_serializable/json_serializable
  json_annotation:
    path: ../../json_serializable/json_annotation