name: rmi_tests
version: 0.0.0
description: >
  TODO, do not publish, update presubmit
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>
homepage: https://github.com/MatzeS/dart_rmi

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^0.33.3
  build: ^1.0.0
  tuple:
  build_config: ^0.3.1
  source_gen: ^0.9.0
  build_runner: ^1.1.2
  rmi:
    path: ../rmi
  
dev_dependencies:
  rmi_generator:
    path: ../rmi_generator
  source_gen_helpers: ^0.0.1
  test: ^1.5.1
  json_serializable:
    git:
      url: https://github.com/MatzeS/json_serializable
      ref: feature/blackbird
      path: json_serializable
